name: deploy

on:
  workflow_run:
    workflows: ["ci"]   
    types: [completed]
    branches: [main]   

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success' 
    
    steps:
      - uses: actions/checkout@v4 

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push to ACR
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/grupo-1-p2-front-devops:latest

      - name: Azure app
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: album-copa-devops
          publish-profile: ${{ secrets.AZ_PUBLISH_PROFILE }}
          image: ${{ secrets.ACR_LOGIN_SERVER }}/grupo-1-p2-front-devops:latest